### ISSUE TITLE
Create random string for alias URL if it is not passed in JSON

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/redirector#3]
As the topic suggests, if the alias URL has not been specified, generate a 6-letter random string (uppercase, lowercase and numbers) for the alias URL

**Comment by ShootGan** [comment]
I want to do this. Can you assign me?

**Comment by aditeyabaral** [comment]
Sure!

**Comment by ShootGan** [comment]
can you add Hacktoberfest label?
