### ISSUE TITLE
Dockerise the project using `docker-compose`

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/redirector#5]
Dockerise the project using docker-compose. Allows the entire application to be quickly deployed and built as well. Ensure the database and everything else is setup at boot time.

**Comment by Marsh-sudo** [comment]
Would love to solve this issue :)

**Comment by satyamsettyeswara** [comment]
Hi, I was trying to run this project. But how do i access the link the new link. From here goto-link/alias_name
